spring.application.name=mmsystem

# Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mmsystem
spring.datasource.username=postgres
spring.datasource.password=admin

# Hibernate - Cria as tabelas automaticamente baseado nas classes Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Permite que o React acesse o Java
server.port=8080